version: "3"
services:
  web:
    build: .
    container_name: pockeybackend
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: always
